### ISSUE TITLE
I can't use it

### ISSUE THREAD

**Issue by devilmac** [instructure/android-ImageSweep#1]
Hi,

I'm trying to use this tool but I don't understand how it work, that is:

I type this on a terminal (I'm in Windows)
G:\Download>python ImageSweep.py G:\Folder_Projects\Project

(where "Project" is the root folder of my Eclipse project)

but I get the error message

  File "....\Download\ImageSweep.py", line 73
    print 'Usage: "python ImageSweep.py project_src_directory"'
SyntaxError: invalid syntax

Could you explain me the correct sintax with an example, please?

Thank you in advance.

Kind regards,

Federico

**Comment by simonista** [comment]
Closing issues in preparation to archive this project.
