### ISSUE TITLE
mipmap-* folders not supported

### ISSUE THREAD

**Issue by bveenvliet** [instructure/android-ImageSweep#4]
Image files in the res\mipmap-\* folders are erased even though I have references to @mipmap/id in my layout xml files.

**Comment by bveenvliet** [comment]
Potential fix here

https://github.com/bveenvliet/android-ImageSweep/commit/5aa4c0fa08cca6ad61a50aea9a7c9bd0d4851188

**Comment by simonista** [comment]
Closing issues in preparation to archive this project.
